/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ZiyaratMadinahRouteImport } from './routes/ziyarat.madinah'
import { Route as ZiyaratMakkahRouteImport } from './routes/ziyarat.makkah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiyaratMadinahRoute = ZiyaratMadinahRouteImport.update({
  id: '/ziyarat/madinah',
  path: '/ziyarat/madinah',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiyaratMakkahRoute = ZiyaratMakkahRouteImport.update({
  id: '/ziyarat/makkah',
  path: '/ziyarat/makkah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/ziyarat/madinah': typeof ZiyaratMadinahRoute
  '/ziyarat/makkah': typeof ZiyaratMakkahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/ziyarat/madinah': typeof ZiyaratMadinahRoute
  '/ziyarat/makkah': typeof ZiyaratMakkahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/ziyarat/madinah': typeof ZiyaratMadinahRoute
  '/ziyarat/makkah': typeof ZiyaratMakkahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offers' | '/ziyarat/madinah' | '/ziyarat/makkah'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offers' | '/ziyarat/madinah' | '/ziyarat/makkah'
  id: '__root__' | '/' | '/offers' | '/ziyarat/madinah' | '/ziyarat/makkah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OffersRoute: typeof OffersRoute
  ZiyaratMadinahRoute: typeof ZiyaratMadinahRoute
  ZiyaratMakkahRoute: typeof ZiyaratMakkahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziyarat/madinah': {
      id: '/ziyarat/madinah'
      path: '/ziyarat/madinah'
      fullPath: '/ziyarat/madinah'
      preLoaderRoute: typeof ZiyaratMadinahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziyarat/makkah': {
      id: '/ziyarat/makkah'
      path: '/ziyarat/makkah'
      fullPath: '/ziyarat/makkah'
      preLoaderRoute: typeof ZiyaratMakkahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OffersRoute: OffersRoute,
  ZiyaratMadinahRoute: ZiyaratMadinahRoute,
  ZiyaratMakkahRoute: ZiyaratMakkahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
